### ISSUE TITLE
Uncaught TypeError: Cannot convert a Symbol value to a string

### ISSUE THREAD

**Issue by joebentaylor1995** [bogdanpetru/react-masonry#7]
getting this error every time i try to use your component

`<Masonry>
                        {itemsToShow.map((block, index) => (
                            <Fragment key={index}>
                                <ProjectCard
                                    slug={block.node.slug}
                                    title={block.node.title}
                                    category={block.node.category}
                                    size={block.node.projectThumbnail}
                                    image={block.node.projectThumbnailImage}
                                />
                            </Fragment>
                        ))}
                    </Masonry>`

**Comment by bogdanpetru** [comment]
Hello, sorry for the very late reply.

The componets inside Mansonry need to be DOM elements, as specified in https://github.com/bogdanpetru/react-masonry#usage.

This component should not be used for any production projects. It is in development
